language: java

#addons:
#  sonarcloud:
#    organization: "sbaltes-github"
#    token: $SONAR_TOKEN

#script:
#  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
